[2023-03-29T18:51:53.809+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.process_user __airflow_temporary_run_2023-03-29T18:51:48.922573+00:00__ [queued]>
[2023-03-29T18:51:53.815+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.process_user __airflow_temporary_run_2023-03-29T18:51:48.922573+00:00__ [queued]>
[2023-03-29T18:51:53.816+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T18:51:53.817+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-03-29T18:51:53.818+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T18:51:53.825+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): process_user> on 2022-01-01 00:00:00+00:00
[2023-03-29T18:51:53.830+0000] {standard_task_runner.py:55} INFO - Started process 17684 to run task
[2023-03-29T18:51:53.833+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'process_user', '__***_temporary_run_2023-03-29T18:51:48.922573+00:00__', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpekx4s2kc']
[2023-03-29T18:51:53.835+0000] {standard_task_runner.py:83} INFO - Job 20: Subtask process_user
[2023-03-29T18:51:53.877+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.process_user __airflow_temporary_run_2023-03-29T18:51:48.922573+00:00__ [running]> on host 9dcb783b1f3a
[2023-03-29T18:51:53.918+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=process_user
AIRFLOW_CTX_EXECUTION_DATE=2022-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=__***_temporary_run_2023-03-29T18:51:48.922573+00:00__
[2023-03-29T18:51:53.927+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/user_processing.py", line 16, in _process_user_
    'firstname': user['name']['first'],
TypeError: string indices must be integers
[2023-03-29T18:51:53.935+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=user_processing, task_id=process_user, execution_date=20220101T000000, start_date=20230329T185153, end_date=20230329T185153
[2023-03-29T18:51:53.942+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 20 for task process_user (string indices must be integers; 17684)
[2023-03-29T18:51:53.969+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-03-29T18:51:53.988+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
